// Generated by https://quicktype.io
// https://docs.microsoft.com/en-us/graph/api/resources/contact?view=graph-rest-1.0

import { EmailAddress } from './email-address.dto';
import { PhysicalAddress } from './physical-address.dto';
import { ProfilePhoto } from './profile-photo.dto';

export interface Contact {
    assistantName: string;
    birthday: string;
    businessAddress: PhysicalAddress;
    businessHomePage: string;
    businessPhones: string[];
    categories: string[];
    changeKey: string;
    children: string[];
    companyName: string;
    createdDateTime: string;
    department: string;
    displayName: string;
    emailAddresses: EmailAddress[];
    fileAs: string;
    generation: string;
    givenName: string;
    homeAddress: PhysicalAddress;
    homePhones: string[];
    id: string;
    imAddresses: string[];
    initials: string;
    jobTitle: string;
    lastModifiedDateTime: string;
    manager: string;
    middleName: string;
    mobilePhone: string;
    nickName: string;
    officeLocation: string;
    otherAddress: PhysicalAddress;
    parentFolderId: string;
    personalNotes: string;
    profession: string;
    spouseName: string;
    surname: string;
    title: string;
    yomiCompanyName: string;
    yomiGivenName: string;
    yomiSurname: string;
    photo: ProfilePhoto;
}
