// Generated by https://quicktype.io
// https://docs.microsoft.com/en-us/graph/api/resources/emailaddress?view=graph-rest-1.0

export interface EmailAddress {
    address: string;
    name: string;
}
