// Generated by https://quicktype.io
// https://docs.microsoft.com/en-us/graph/api/resources/physicaladdress?view=graph-rest-1.0

export interface PhysicalAddress {
    city: string;
    countryOrRegion: string;
    postalCode: string;
    state: string;
    street: string;
}
