// Generated by https://quicktype.io

import { Message } from './get_all_threads.dto';

export interface GetAllMessagesThreadBase {
    id: string;
}

export interface GetAllMessagesThread extends GetAllMessagesThreadBase {
    t_read: string;
}

export interface GetAllMessagesDTO<
    T extends GetAllMessagesThreadBase = GetAllMessagesThreadBase
> {
    thread: T;
    messages: Message[];
    return: number;
    desc: string;
}
