// Generated by https://quicktype.io

export interface AddE911SubscriberDTO {
    root: Root;
}

export interface Root {
    return: string;
    desc: Desc;
}

export interface Desc {
    'prov:AddSubscrResp': ProvAddSubscrResp;
}

export interface ProvAddSubscrResp {
    '-xmlns:prov': string;
    'prov:RqstId': string;
    'prov:SubscriberID': string;
    'prov:LocStatus': ProvLOCStatus;
}

export interface ProvLOCStatus {
    'prov:VDBinvalid': ProvVDBinvalid;
}

export interface ProvVDBinvalid {
    'prov:VDBalternative': ProvVDBalternative;
}

export interface ProvVDBalternative {
    'urn:civicAddress': { [key: string]: string };
}
