// Generated by https://quicktype.io

export interface AddUserDeviceResponseDto {
    root: {
        device_data: DeviceData;
        api_token: string;
        connection_info: ConnectionInfo;
        return: string;
        desc: string;
    };
}

export interface GetOtpResponseDto {
    root: {
        otp: string;
        return: string;
        desc: string;
    };
}

export interface ConnectionInfo {
    stun_url: string;
    turn_url: string;
    turn_username: string;
    turn_password: string;
    asterisk_ip: string;
    ws_port: string;
    wss_port: string;
    outbound_proxy_port: string;
    sec_stun_url: string;
    sec_asterisk_ip: any[];
    sec_ws_port: string;
    sec_wss_port: string;
    sec_outbound_proxy_port: string;
}

export interface DeviceData {
    sip_username: string;
    sip_password: string;
    sip_address: string;
    adk_address: string;
    stun_address: string;
    sip_reg_interval: string;
    auth_required: string;
    device_type: string;
    transport: string;
    sms_capable: string;
    secure_enabled: string;
    capabilities: Capabilities;
}

export interface Capabilities {
    wifi_only: string;
    diagnostics: string;
    minimum_client_version: string;
    allowed_application_names: string;
    pending_events: string;
}
