// Generated by https://quicktype.io

export interface GetStatusE911DTO {
    root: Root;
}

export interface Root {
    return: string;
    desc: string;
    e911_status: string;
    e911_status_updated_at: string;
}
