// Generated by https://quicktype.io

export interface GetNumbersResponseDTO {
    root: GetNumbersRoot;
}

export interface GetNumbersRoot {
    sl_number: string | string[];
    return:    string;
    desc:      string;
}
