// Generated by https://quicktype.io

export interface GetUserInfoResponseDTO {
    root: {
        gdpr_compliant: string;
        gdpr_deferred: string;
        gdpr_deferred_timestamp: string;
        number_of_ids_allowed: string;
        current_time: string;
        sls_num_data: SlsNumData;
        number_of_participants: string;
        max_mms_size: string;
        max_api_msg_count: string;
        hide_terms_privacy_policy: string;
        return: string;
        desc: string;
        c_key: string;
        c_value: string;
        adk_address: string;
    };
}

export interface SlsNumData {
    sls_number: string;
    sls_sms_enabled: string;
    sls_enable: string;
    tui_password: any[];
    orgid: string;
    organization_id: string;
    prepaid: string;
    voicemail_allowed: string;
    vvm_enabled: string;
    e911_support_enable: string;
    allow_call_transfer: string;
    sms_only: string;
    call_forwarding_required_while_onboard: string;
    brandings_last_updated: string;
    mos_threshold: string;
    mos_occurrence_threshold: string;
    message_popup: any[];
    inbound_calls_allow_data: string;
    inbound_calls_allow_minutes: string;
    inbound_calls_allow_fallback: string;
    outbound_calls_allow_data: string;
    outbound_calls_allow_minutes: string;
    outbound_calls_allow_choose_on_dialer: string;
    outbound_calls_hide_tdm: string;
    default_inbound_calling: string;
    default_outbound_calling: string;
    contacts_allow_use_native: string;
    contacts_allow_import_native: string;
    contacts_allow_exchange: string;
    allow_line_name_change: string;
    allow_call_forwarding: string;
    allow_time_of_day_scheduling: string;
    allow_cli_restriction: string;
    allow_broadcast_calling: string;
    allow_zombie_wifi: string;
    allow_blacklist: string;
    vvm_allow_spoken_name_recording: string;
    vvm_allow_custom_greeting_recording: string;
    v2t_allow: string;
    number_of_sms_recipients: string;
    gdpr_suspended: string;
    gdpr_suspended_timestamp: string;
    forwarding_number: any[];
    suspended: string;
    enable_picture_message: string;
    enable_group_message: string;
    external_invoke_apps: string;
    e911_last_called: any[];
    whatsapp_config: any[];
    allow_sms: 'true' | 'false';
    allow_webrtc_calls: 'true' | 'false';
}
