// Generated by https://quicktype.io

export interface LookupE911SubscriberDTO {
    root: {
        return: string;
        desc:   Desc;
    }
}

export interface Desc {
    QrySubscrResp: QrySubscrResp;
}

export interface QrySubscrResp {
    RqstId:     string;
    Subscriber: Subscriber;
}

export interface Subscriber {
    SubscriberID:    string;
    SubscrName:      string;
    CBN:             string;
    Location:        Location;
    LocStatus:       LOCStatus;
    LastProvisioned: string;
}

export interface LOCStatus {
    VDBvalid: VDBvalid;
}

export interface VDBvalid {
    VDBposition: VDBposition;
}

export interface VDBposition {
    Latitude:  string;
    Longitude: string;
}

export interface Location {
    civicAddress: CivicAddress;
}

export interface CivicAddress {
    country: string;
    A1:      string;
    RD:      string;
    HNO:     string;
    LOC:     null;
    PC:      string;
    PCN:     string;
}
